<?php
function support_theme_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');register_nav_menus(['primary'=>'메인']);}
add_action('after_setup_theme','support_theme_setup');
function support_enqueue_scripts(){wp_enqueue_style('support-style',get_stylesheet_uri());}
add_action('wp_enqueue_scripts','support_enqueue_scripts');
function register_support_card_cpt(){register_post_type('support_card',['labels'=>['name'=>'지원금 카드','singular_name'=>'카드','add_new'=>'새 카드'],'public'=>true,'has_archive'=>false,'menu_icon'=>'dashicons-money-alt','supports'=>['title','editor'],'show_in_rest'=>true]);}
add_action('init','register_support_card_cpt');
function add_support_card_meta_boxes(){add_meta_box('support_card_details','카드 정보','render_support_card_meta_box','support_card','normal','high');}
add_action('add_meta_boxes','add_support_card_meta_boxes');
function render_support_card_meta_box($post){wp_nonce_field('support_card_save','support_card_nonce');$amount=get_post_meta($post->ID,'_card_amount',true);$amount_sub=get_post_meta($post->ID,'_card_amount_sub',true);$target=get_post_meta($post->ID,'_card_target',true);$period=get_post_meta($post->ID,'_card_period',true);$link=get_post_meta($post->ID,'_card_link',true);$featured=get_post_meta($post->ID,'_card_featured',true);?>
<style>.sp-field{margin:15px 0}.sp-field label{display:block;font-weight:600;margin-bottom:5px}.sp-field input{width:100%;padding:8px;border:1px solid #ddd;border-radius:4px}.sp-btn{background:linear-gradient(135deg,#2563EB 0%,#7C3AED 100%);color:#fff;border:none;padding:12px 24px;border-radius:6px;font-weight:700;cursor:pointer;margin:10px 0}.sp-notice{background:#FEF3C7;padding:12px;margin:15px 0;border-left:4px solid #F59E0B;border-radius:4px}</style>
<div class="sp-notice"><strong>🤖 자동 생성:</strong> 키워드 입력 후 버튼 클릭!<br><small>청년도약계좌, 청년내일채움공제, 근로장려금, 자녀장려금, 청년월세지원, 기초연금, 출산지원금, 실업급여</small></div>
<div class="sp-field"><label>📌 키워드</label><input type="text" id="sp_kw" placeholder="예: 청년도약계좌"/></div>
<button type="button" class="sp-btn" onclick="spGen()">✨ 생성</button>
<div id="sp_st" style="padding:10px;margin:10px 0;border-radius:4px;display:none"></div>
<script>
var T={'청년도약계좌':{t:'청년도약계좌 - 5년 만기 시 최대 5,000만원',a:'최대 5,000만원',s:'정부 기여금+이자',d:'<h2>청년 미래 특별 기회</h2><p>월 70만원 납입 시 정부 6% 기여금 추가!</p><h3>✅ 주요 혜택</h3><ul><li>5년 만기 최대 5,000만원</li><li>정부 기여금 지원</li><li>비과세 혜택</li></ul><h3>🎯 자격</h3><p>만 19~34세, 소득 7,500만원 이하</p><p><strong>선착순 마감! 지금 신청하세요!</strong></p>',tg:'만 19~34세 청년',p:'상시(선착순)',l:'https://www.youthaccount.kr'},'청년내일채움공제':{t:'청년내일채움공제 - 2년 근속 시 1,600만원',a:'최대 1,600만원',s:'정부+기업',d:'<h2>중소기업 청년 목돈</h2><p>2년 근속으로 1,600만원!</p><h3>💰 구성</h3><ul><li>본인: 400만원</li><li>정부: 900만원</li><li>기업: 300만원</li><li>총 1,600만원</li></ul><h3>✅ 자격</h3><p>만 15~34세 중소기업 정규직</p>',tg:'중소기업 청년',p:'기업 참여 시',l:'https://www.work.go.kr/jobgong'},'근로장려금':{t:'근로장려금 - 최대 330만원 현금',a:'최대 330만원',s:'연 1회 현금',d:'<h2>저소득 근로자 현금 지원</h2><h3>💵 금액</h3><ul><li>단독: 최대 165만원</li><li>홑벌이: 285만원</li><li>맞벌이: 330만원</li></ul><h3>📅 신청</h3><p>5월 정기, 9월 반기 신청</p><p>신청만 하면 계좌 입금!</p>',tg:'저소득 근로자',p:'5월,9월',l:'https://www.nts.go.kr/eitc'},'자녀장려금':{t:'자녀장려금 - 자녀당 100만원',a:'자녀당 100만원',s:'현금',d:'<h2>자녀 양육 현금 지원</h2><p>자녀 1명당 100만원!</p><h3>✅ 중복 가능</h3><p>근로장려금과 함께 최대 600만원 이상</p><h3>📋 자격</h3><p>소득 4,000만원 미만, 18세 미만 자녀</p>',tg:'저소득 가구(자녀有)',p:'5월',l:'https://www.nts.go.kr/ctc'},'청년월세지원':{t:'청년월세 지원 - 월 20만원x12개월',a:'최대 240만원',s:'월 20만원x12',d:'<h2>월세 부담 해결</h2><p>매월 20만원씩 12개월!</p><h3>✅ 자격</h3><ul><li>만 19~34세 무주택</li><li>독립 거주</li><li>본인 소득 기준</li></ul><p>부모 소득 무관!</p>',tg:'만 19~34세',p:'예산 소진 시 마감',l:'https://www.bokjiro.go.kr'},'기초연금':{t:'기초연금 - 매월 334,810원',a:'월 334,810원',s:'평생 매월',d:'<h2>어르신 평생 연금</h2><p>만 65세 이상 매월 334,810원</p><h3>✅ 자격</h3><p>만 65세 이상, 소득 하위 70%</p><h3>📅 신청</h3><p>생일 1개월 전부터 가능</p>',tg:'만 65세 이상',p:'생일 1개월 전',l:'https://basicpension.mohw.go.kr'},'출산지원금':{t:'출산지원금 - 첫째 200만원',a:'첫째 200만원',s:'둘째 300만원',d:'<h2>출산 가정 현금</h2><h3>💰 금액</h3><ul><li>첫째: 200만원</li><li>둘째: 300만원</li><li>셋째: 500만원+</li></ul><h3>📋 신청</h3><p>출산 후 60일 이내</p><p>지자체 추가 지원도 확인!</p>',tg:'출산 가정',p:'출산 후 60일',l:'https://www.bokjiro.go.kr'},'실업급여':{t:'실업급여 - 최대 1,782만원',a:'최대 1,782만원',s:'최대 270일',d:'<h2>실직자 생활 안정</h2><p>평균임금 60% 지급</p><h3>📅 기간</h3><ul><li>50세 미만: 120~240일</li><li>50세 이상: 최대 270일</li></ul><h3>⚠️ 기한</h3><p>퇴직 후 12개월 이내 신청!</p>',tg:'실직자(고용보험)',p:'퇴직 후 12개월',l:'https://www.ei.go.kr'}};
function spGen(){var k=document.getElementById('sp_kw').value.trim(),s=document.getElementById('sp_st');if(!k){s.style.cssText='display:block;background:#fee;border:2px solid #f00;color:#c00';s.innerHTML='❌ 키워드 필요';return}s.style.cssText='display:block;background:#fef3c7;border:2px solid #f59e0b;color:#92400e';s.innerHTML='⏳ 생성 중...';setTimeout(function(){var r=T[k]||{t:k+' - 지금 신청',a:'최대 300만원',s:'정부 지원',d:'<h2>'+k+'</h2><p>정부 지원 혜택입니다.</p><p>조건 충족 시 신청 가능합니다.</p>',tg:'대한민국 국민',p:'상시',l:'https://www.bokjiro.go.kr'};document.getElementById('card_amount').value=r.a;document.getElementById('card_amount_sub').value=r.s;document.getElementById('card_target').value=r.tg;document.getElementById('card_period').value=r.p;document.getElementById('card_link').value=r.l||'';var ti=document.getElementById('title');if(ti)ti.value=r.t;if(typeof tinymce!=='undefined'&&tinymce.get('content')){tinymce.get('content').setContent(r.d);tinymce.get('content').save()}else{var c=document.getElementById('content');if(c)c.value=r.d}var ta=document.querySelector('textarea#content');if(ta){ta.value=r.d;ta.dispatchEvent(new Event('input',{bubbles:true}))}s.style.cssText='display:block;background:#d1fae5;border:2px solid #10b981;color:#065f46';s.innerHTML='✅ 완료! 이제 발행 버튼만 누르세요!'},400)}
</script>
<hr style="margin:20px 0;border:none;border-top:1px solid #ddd"/>
<div class="sp-field"><label>💰 금액</label><input type="text" name="card_amount" id="card_amount" value="<?php echo esc_attr($amount);?>"/></div>
<div class="sp-field"><label>💬 부가</label><input type="text" name="card_amount_sub" id="card_amount_sub" value="<?php echo esc_attr($amount_sub);?>"/></div>
<div class="sp-field"><label>👥 대상</label><input type="text" name="card_target" id="card_target" value="<?php echo esc_attr($target);?>"/></div>
<div class="sp-field"><label>📅 기간</label><input type="text" name="card_period" id="card_period" value="<?php echo esc_attr($period);?>"/></div>
<div class="sp-field"><label>🔗 URL</label><input type="url" name="card_link" id="card_link" value="<?php echo esc_attr($link);?>"/></div>
<div class="sp-field"><label><input type="checkbox" name="card_featured" value="1" <?php checked($featured,'1');?>/> 🔥 인기</label></div>
<?php }
function save_support_card_meta($post_id){if(!isset($_POST['support_card_nonce'])||!wp_verify_nonce($_POST['support_card_nonce'],'support_card_save'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;$fields=['card_amount','card_amount_sub','card_target','card_period','card_link'];foreach($fields as $f)if(isset($_POST[$f]))update_post_meta($post_id,'_'.$f,sanitize_text_field($_POST[$f]));update_post_meta($post_id,'_card_featured',isset($_POST['card_featured'])?'1':'0');}
add_action('save_post_support_card','save_support_card_meta');
