<?php
function support_theme_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');register_nav_menus(['primary'=>'메인']);}
add_action('after_setup_theme','support_theme_setup');
function support_enqueue_scripts(){wp_enqueue_style('support-style',get_stylesheet_uri());}
add_action('wp_enqueue_scripts','support_enqueue_scripts');
function register_support_card_cpt(){register_post_type('support_card',['labels'=>['name'=>'지원금 카드','singular_name'=>'카드','add_new'=>'새 카드'],'public'=>true,'has_archive'=>false,'menu_icon'=>'dashicons-money-alt','supports'=>['title','editor','custom-fields'],'show_in_rest'=>true]);}
add_action('init','register_support_card_cpt');
function add_support_card_meta_boxes(){add_meta_box('support_card_details','카드 정보','render_support_card_meta_box','support_card','normal','high');}
add_action('add_meta_boxes','add_support_card_meta_boxes');
function render_support_card_meta_box($post){wp_nonce_field('support_card_save','support_card_nonce');$amount=get_post_meta($post->ID,'_card_amount',true);$amount_sub=get_post_meta($post->ID,'_card_amount_sub',true);$target=get_post_meta($post->ID,'_card_target',true);$period=get_post_meta($post->ID,'_card_period',true);$link=get_post_meta($post->ID,'_card_link',true);$featured=get_post_meta($post->ID,'_card_featured',true);?>
<style>.sp-field{margin:15px 0}.sp-field label{display:block;font-weight:600;margin-bottom:5px}.sp-field input{width:100%;padding:8px;border:1px solid #ddd;border-radius:4px}.sp-btn{background:linear-gradient(135deg,#2563EB 0%,#7C3AED 100%);color:#fff;border:none;padding:15px 30px;border-radius:8px;font-weight:700;cursor:pointer;margin:10px 0;font-size:16px}.sp-btn:hover{background:linear-gradient(135deg,#1E40AF 0%,#6D28D9 100%)}.sp-notice{background:#FEF3C7;padding:15px;margin:15px 0;border-left:4px solid #F59E0B;border-radius:4px}.sp-alert{padding:15px;margin:15px 0;border-radius:8px;font-weight:600}</style>
<div class="sp-notice"><strong>🤖 자동 생성 시스템</strong><br>키워드 입력 → 생성 버튼 → 제목과 내용이 자동 작성됨<br><small style="color:#92400e">청년도약계좌, 청년내일채움공제, 근로장려금, 자녀장려금, 청년월세지원, 기초연금, 출산지원금, 실업급여</small></div>
<div class="sp-field"><label style="font-size:16px">📌 키워드 입력</label><input type="text" id="sp_kw" placeholder="예: 청년도약계좌" style="font-size:15px"/></div>
<button type="button" class="sp-btn" onclick="spAutoFill()">✨ 자동 생성하기</button>
<div id="sp_status"></div>
<script>
var DATA={'청년도약계좌':{t:'청년도약계좌 - 5년 만기 시 최대 5,000만원',a:'최대 5,000만원',s:'정부 기여금+이자',c:'월 70만원 납입 시 정부 6% 기여금 추가! 5년 만기 최대 5,000만원. 정부 기여금 지원, 비과세 혜택. 만 19~34세, 소득 7,500만원 이하. 선착순 마감! 지금 신청하세요!',tg:'만 19~34세 청년',p:'상시(선착순)',l:'https://www.youthaccount.kr'},'청년내일채움공제':{t:'청년내일채움공제 - 2년 근속 시 1,600만원',a:'최대 1,600만원',s:'정부+기업',c:'중소기업 청년 목돈 마련! 2년 근속으로 1,600만원! 본인 400만원 + 정부 900만원 + 기업 300만원 = 총 1,600만원. 만 15~34세 중소기업 정규직.',tg:'중소기업 청년',p:'기업 참여 시',l:'https://www.work.go.kr/jobgong'},'근로장려금':{t:'근로장려금 - 최대 330만원 현금',a:'최대 330만원',s:'연 1회 현금',c:'저소득 근로자 현금 지원. 단독 최대 165만원, 홑벌이 285만원, 맞벌이 330만원. 5월 정기, 9월 반기 신청. 신청만 하면 계좌 입금!',tg:'저소득 근로자',p:'5월,9월',l:'https://www.nts.go.kr/eitc'},'자녀장려금':{t:'자녀장려금 - 자녀당 100만원',a:'자녀당 100만원',s:'현금',c:'자녀 양육 현금 지원. 자녀 1명당 100만원! 근로장려금과 중복 가능, 최대 600만원 이상. 소득 4,000만원 미만, 18세 미만 자녀.',tg:'저소득 가구(자녀有)',p:'5월',l:'https://www.nts.go.kr/ctc'},'청년월세지원':{t:'청년월세 지원 - 월 20만원x12개월',a:'최대 240만원',s:'월 20만원x12',c:'월세 부담 해결! 매월 20만원씩 12개월! 만 19~34세 무주택 독립 거주, 본인 소득 기준. 부모 소득 무관!',tg:'만 19~34세',p:'예산 소진 시 마감',l:'https://www.bokjiro.go.kr'},'기초연금':{t:'기초연금 - 매월 334,810원',a:'월 334,810원',s:'평생 매월',c:'어르신 평생 연금. 만 65세 이상 매월 334,810원. 만 65세 이상, 소득 하위 70%. 생일 1개월 전부터 신청 가능.',tg:'만 65세 이상',p:'생일 1개월 전',l:'https://basicpension.mohw.go.kr'},'출산지원금':{t:'출산지원금 - 첫째 200만원',a:'첫째 200만원',s:'둘째 300만원',c:'출산 가정 현금 지원. 첫째 200만원, 둘째 300만원, 셋째 500만원 이상. 출산 후 60일 이내 신청. 지자체 추가 지원도 확인!',tg:'출산 가정',p:'출산 후 60일',l:'https://www.bokjiro.go.kr'},'실업급여':{t:'실업급여 - 최대 1,782만원',a:'최대 1,782만원',s:'최대 270일',c:'실직자 생활 안정 지원. 평균임금 60% 지급. 50세 미만 120~240일, 50세 이상 최대 270일. 퇴직 후 12개월 이내 신청 필수!',tg:'실직자(고용보험)',p:'퇴직 후 12개월',l:'https://www.ei.go.kr'}};
function spAutoFill(){var k=document.getElementById('sp_kw').value.trim(),st=document.getElementById('sp_status');if(!k){st.innerHTML='<div class="sp-alert" style="background:#fee;color:#c00;border:2px solid #f00">❌ 키워드를 입력하세요</div>';return}st.innerHTML='<div class="sp-alert" style="background:#fef3c7;color:#92400e;border:2px solid #f59e0b">⏳ 생성 중...</div>';setTimeout(function(){var d=DATA[k]||{t:k+' - 지금 신청',a:'최대 300만원',s:'정부 지원',c:k+' 정부 지원 혜택입니다. 조건 충족 시 신청 가능합니다.',tg:'대한민국 국민',p:'상시',l:'https://www.bokjiro.go.kr'};document.getElementById('card_amount').value=d.a;document.getElementById('card_amount_sub').value=d.s;document.getElementById('card_target').value=d.tg;document.getElementById('card_period').value=d.p;document.getElementById('card_link').value=d.l;wp.data.dispatch('core/editor').editPost({title:d.t,content:d.c});st.innerHTML='<div class="sp-alert" style="background:#d1fae5;color:#065f46;border:2px solid #10b981">✅ 생성 완료! 위에서 제목과 내용을 확인하고 발행 버튼을 누르세요!</div>'},500)}
</script>
<hr style="margin:20px 0;border:none;border-top:1px solid #ddd"/>
<div class="sp-field"><label>💰 금액</label><input type="text" name="card_amount" id="card_amount" value="<?php echo esc_attr($amount);?>"/></div>
<div class="sp-field"><label>💬 부가</label><input type="text" name="card_amount_sub" id="card_amount_sub" value="<?php echo esc_attr($amount_sub);?>"/></div>
<div class="sp-field"><label>👥 대상</label><input type="text" name="card_target" id="card_target" value="<?php echo esc_attr($target);?>"/></div>
<div class="sp-field"><label>📅 기간</label><input type="text" name="card_period" id="card_period" value="<?php echo esc_attr($period);?>"/></div>
<div class="sp-field"><label>🔗 URL</label><input type="url" name="card_link" id="card_link" value="<?php echo esc_attr($link);?>"/></div>
<div class="sp-field"><label><input type="checkbox" name="card_featured" value="1" <?php checked($featured,'1');?>/> 🔥 인기</label></div>
<?php }
function save_support_card_meta($post_id){if(!isset($_POST['support_card_nonce'])||!wp_verify_nonce($_POST['support_card_nonce'],'support_card_save'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;$fields=['card_amount','card_amount_sub','card_target','card_period','card_link'];foreach($fields as $f)if(isset($_POST[$f]))update_post_meta($post_id,'_'.$f,sanitize_text_field($_POST[$f]));update_post_meta($post_id,'_card_featured',isset($_POST['card_featured'])?'1':'0');}
add_action('save_post_support_card','save_support_card_meta');
